package com.myspace.rcm;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RequestForInfo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("User Name")
	private java.lang.String user;
	@org.kie.api.definition.type.Label("RFI Number")
	private java.lang.String rfiNum;
	@org.kie.api.definition.type.Label("Name of Request")
	private java.lang.String requestName;
	@org.kie.api.definition.type.Label("Request Description")
	private java.lang.String requestDescription;
	@org.kie.api.definition.type.Label("National Intelligent Priority")
	private java.lang.String nip;
	@org.kie.api.definition.type.Label("Last Time Information is of Value")
	private java.lang.String ltiov;
	@org.kie.api.definition.type.Label(value = "Email Address")
	private java.lang.String email;

	public RequestForInfo() {
	}

	public java.lang.String getUser() {
		return this.user;
	}

	public void setUser(java.lang.String user) {
		this.user = user;
	}

	public java.lang.String getRfiNum() {
		return this.rfiNum;
	}

	public void setRfiNum(java.lang.String rfiNum) {
		this.rfiNum = rfiNum;
	}

	public java.lang.String getRequestName() {
		return this.requestName;
	}

	public void setRequestName(java.lang.String requestName) {
		this.requestName = requestName;
	}

	public java.lang.String getRequestDescription() {
		return this.requestDescription;
	}

	public void setRequestDescription(java.lang.String requestDescription) {
		this.requestDescription = requestDescription;
	}

	public java.lang.String getNip() {
		return this.nip;
	}

	public void setNip(java.lang.String nip) {
		this.nip = nip;
	}

	public java.lang.String getLtiov() {
		return this.ltiov;
	}

	public void setLtiov(java.lang.String ltiov) {
		this.ltiov = ltiov;
	}


	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("user: ");
		builder.append(user);
		builder.append('\n');
		builder.append("rfiNum: ");
		builder.append(rfiNum);
		builder.append('\n');
		builder.append("requestName: ");
		builder.append(requestName);
		builder.append('\n');
		builder.append("requestDescription: ");
		builder.append(requestDescription);
		builder.append('\n');
		builder.append("nip: ");
		builder.append(nip);
		builder.append('\n');
		builder.append("ltiov: ");
		builder.append(ltiov);
		builder.append('\n');
		builder.append("email: ");
		builder.append(email);
		builder.append('\n');
		return builder.toString();
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}

	public RequestForInfo(java.lang.String user, java.lang.String rfiNum,
			java.lang.String requestName, java.lang.String requestDescription,
			java.lang.String nip, java.lang.String ltiov, java.lang.String email) {
		this.user = user;
		this.rfiNum = rfiNum;
		this.requestName = requestName;
		this.requestDescription = requestDescription;
		this.nip = nip;
		this.ltiov = ltiov;
		this.email = email;
	}

}