package com.myspace.rcm;

import java.lang.Number;
import java.text.SimpleDateFormat;

function long toMinutes(String dateString) {
    SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss");
    return formatter.parse(dateString.substring(0, 19)).getTime() / 60000;
}

rule "Validate user"
	dialect "mvel"
	ruleflow-group "validateInput"
	no-loop
	when
		app : RequestForInfo( user.length() == 0 )
	then
		System.out.println("Executed Rule: " + drools.getRule().getName() );
		insert(new ValidationError("user cannot be null"));
end

rule "Validate rfiNum"
	dialect "mvel"
	ruleflow-group "validateInput"
	no-loop
	when
		app : RequestForInfo( rfiNum.length() == 0 )
	then
		System.out.println("Executed Rule: " + drools.getRule().getName() );
		insert(new ValidationError("rfiNum cannot be null"))
end

rule "Validate requestName"
	dialect "mvel"
	ruleflow-group "validateInput"
	no-loop
	when
		app : RequestForInfo( requestName.length() == 0 )
	then
		System.out.println("Executed Rule: " + drools.getRule().getName() );
		insert(new ValidationError("requestName cannot be null"))
end

rule "Validate nip"
	dialect "mvel"
	ruleflow-group "validateInput"
	no-loop
	when
		//app : com.myspace.rcm.RequestForInfo( !nip.matches( "^NIP[1-4]{1}$" ) )
		RequestForInfo( nip.length() == 0 )
	then
		System.out.println("Executed Rule: " + drools.getRule().getName() );
		insert(new ValidationError("nip malformed or null"))
end

rule "Validate ltiov"
	dialect "mvel"
	ruleflow-group "validateInput"
	no-loop
	when
		//app : RequestForInfo(  !ltiov.matches("^[0-9]{4}\\\\-[0-9]{2}\\\\-[0-9]{2}T{0-9]{2}:[0-9]{2}:[0-9]{2}$"))
		RequestForInfo( ltiov.length() == 0)
	then
		System.out.println("Executed Rule: " + drools.getRule().getName() );
		insert(new ValidationError("ltiov malformed or null"))
end

rule "Validate email"
	dialect "mvel"
	ruleflow-group "validateInput"
	no-loop
	when
		//app : RequestForInfo( email.matches("^[a-z0-9]+@[a-z0-9\.]+$" ))
	    //RequestForInfo( !email.matches("^[a-z0-9]+\\\\@[a-z0-9\\\\.]+$"))
	    RequestForInfo( email.length() == 0)
	then
		System.out.println("Executed Rule: " + drools.getRule().getName() );
		insert(new ValidationError("email address malformed or null "))
end


/*
rule "Set Error"
	dialect "mvel"
	ruleflow-group "validateInput"
	salience -10
	when
		app : RequestForInfo( errors.length() > 0 )
	then
		//ValidationError fact0 = new ValidationError();
		//fact0.setError( "user is null" );
		//insert( fact0 );
		System.out.println("Executed Rule: " + drools.getRule().getName() );
		insert(new ValidationError(app.getErrors()));
end
*/